require(data.table)
require(ROCR)
require(xlsx)
require(ggplot2)
require(dplyr)
data <- fread("C:/Users/STS-512/Desktop/export.csv")
data$status <- with(data, ifelse(data$status == "N", 0, 1))
data$COC <- (data$TRAINCOC/100)
pred <- prediction(data$COC, data$status)
perf <- performance(pred, "tpr", "fpr")
gain <- performance(pred, "tpr", "rpp")
auc <- performance(pred, measure = "auc") 
gini <- round(2 * auc@y.values[[1]] - 1, 3)
gini <- as.data.frame(gini)
names(gini) <- "Gini_Co-efficient"
png('Gain.png')
plot(gain, colorize = TRUE, lwd = 3, main = "Gains Chart")
dev.off()
png('ROC.png')
plot(perf, colorize = TRUE, lwd = 3, main = "ROC Curves") + abline(a = 0, b = 1, lty = 2, lwd = 3, col = "black")
dev.off()
cutoffs <- data.frame(Cutt_Off = perf@alpha.values[[1]], FPR = perf@x.values[[1]], TPR = perf@y.values[[1]])
cutoffs$TNR <- (1 - cutoffs$FPR)
cutoffs$TOTAL <- cutoffs$TNR + cutoffs$TPR
cutoffs <- cutoffs[order(cutoffs$TOTAL, decreasing = TRUE),]
cutoffs$Cutt_Off <- round(cutoffs$Cutt_Off, 3)
cutoffs$FPR <- round(cutoffs$FPR, 3)
cutoffs$TNR <- round(cutoffs$TNR, 3)
cutoffs$TPR <- round(cutoffs$TPR, 3)
cutoffs$TOTAL <- round(cutoffs$TOTAL, 3)
cutoffValue <- cutoffs[1,1]
data$PREDICT <- with(data, ifelse(data$COC > cutoffValue, 1, 0))
decile <- data %>% filter(PREDICT == 1) %>% arrange(desc(COC)) %>% mutate(Decile = ntile(COC, 10)) %>% group_by(Decile) %>% summarise(Min_COC = min(COC), Max_COC = max(COC), Churn = sum(status == 1), Non_Churn = sum(status == 0)) %>% arrange(desc(Decile))
decile$TOTAL <- decile$Churn + decile$Non_Churn
decile$Churn_Rate <- decile$Churn/decile$TOTAL
decile$Churn_Percentage <- decile$Churn/sum(decile$Churn)
decile$Cum_Churn_Percentage <- cumsum(decile$Churn_Percentage)
decile$Non_Churn_Percentage <- decile$Non_Churn/sum(decile$Non_Churn)
decile$Cum_NonChurn_Percentage <- cumsum(decile$Non_Churn_Percentage)
decile$KS_Score <- abs(decile$Cum_Churn_Percentage - decile$Cum_NonChurn_Percentage)
decile$Min_COC <- round(decile$Min_COC, 3)
decile$Max_COC <- round(decile$Max_COC, 3)
decile$Churn <- format(decile$Churn, big.mark = ",")
decile$Non_Churn <- format(decile$Non_Churn, big.mark = ",")
decile$TOTAL <- format(decile$TOTAL, big.mark = ",")
decile$Churn_Rate <- sprintf("%.2f %%", 100 * decile$Churn_Rate)
decile$Churn_Percentage <- sprintf("%.2f %%", 100 * decile$Churn_Percentage)
decile$Non_Churn_Percentage <- sprintf("%.2f %%", 100 * decile$Non_Churn_Percentage)
decile$Cum_NonChurn_Percentage <- sprintf("%.2f %%", 100 * decile$Cum_NonChurn_Percentage)
decile$KS_Score <- sprintf("%.2f %%", 100 * decile$KS_Score)
RandomModel <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)
Lift <- decile$Cum_Churn_Percentage/RandomModel
RandomModel <- RandomModel * 100
decile$Cum_Churn_Percentage <- sprintf("%.2f %%", 100 * decile$Cum_Churn_Percentage)
Baseline <- rep(1,10)
liftFrame <- data.frame(RandomModel, Lift, Baseline)
png('Lift.png')
p <- ggplot(data = liftFrame, aes(x = RandomModel, y = Lift, group = 1)) + geom_line(color = "red") + geom_point() 
p + labs(title = "Lift Chart",x = "Decile", y = "Lift")
dev.off()
liftFrame$RandomModel <- sprintf("%.2f %%",liftFrame$RandomModel)
liftFrame$Lift <- round(liftFrame$Lift, 3)
wb <- createWorkbook()
sheet1 <- createSheet(wb, sheetName = "ROC Curve")
sheet2 <- createSheet(wb, sheetName = "Gain Chart")
sheet3 <- createSheet(wb, sheetName = "TPR vs FPR")
sheet4 <- createSheet(wb, sheetName = "Decile Chart")
sheet5 <- createSheet(wb, sheetName = "Lift Chart")
TABLE_COLNAMES_STYLE <- CellStyle(wb) + Fill(foregroundColor = "#0014AA")+ Font(wb, heightInPoints=10,isBold=TRUE,color ="9", name="Arial") + Alignment(wrapText=TRUE, horizontal="ALIGN_CENTER") + Border(color="#0014AA", position=c("TOP","RIGHT","BOTTOM","LEFT"), pen=c("BORDER_THICK","BORDER_THICK","BORDER_THICK","BORDER_THICK")) 
CS2<-CellStyle(wb) + Alignment(horizontal="ALIGN_CENTER") + Border(color="black", position=c("TOP","RIGHT","BOTTOM","LEFT"), pen=c("BORDER_THIN","BORDER_THIN","BORDER_THIN","BORDER_THIN")) 
CS1<-CellStyle(wb) + Alignment(horizontal="ALIGN_RIGHT") + Border(color="black", position=c("TOP","RIGHT","BOTTOM","LEFT"), pen=c("BORDER_THIN","BORDER_THIN","BORDER_THIN","BORDER_THIN")) 
addPicture("ROC.png", sheet1, scale = 1, startRow = 3,startColumn = 1)
addPicture("Gain.png", sheet2, scale = 1, startRow = 3,startColumn = 1)
addDataFrame(decile, sheet4, startRow = 3, startColumn = 1, colnamesStyle = TABLE_COLNAMES_STYLE, colStyle=list(`1`=CS2,`2`=CS2,`3`=CS1,`4`=CS1,`5`=CS1,`6`=CS1,`7`=CS1,`8`=CS1,`9`=CS1,`10`=CS1,`11`=CS1,`12`=CS1,`13`=CS1,`14`=CS1,`15`=CS1))
autoSizeColumn(sheet4, colIndex=c(1:17))
addDataFrame(gini, sheet4, startRow = 15, startColumn = 11, colnamesStyle = TABLE_COLNAMES_STYLE, colStyle = list(`1`=CS2,`2`=CS2))
addDataFrame(cutoffs, sheet3, startRow = 3, startColumn = 1, colnamesStyle = TABLE_COLNAMES_STYLE, colStyle=list(`1`=CS2,`2`=CS2,`3`=CS1,`4`=CS1,`5`=CS1,`6`=CS1,`7`=CS1,`8`=CS1,`9`=CS1,`10`=CS1,`11`=CS1,`12`=CS1,`13`=CS1,`14`=CS1,`15`=CS1))
addDataFrame(liftFrame, sheet5, startRow = 3, startColumn = 1, colnamesStyle = TABLE_COLNAMES_STYLE, colStyle=list(`1`=CS2,`2`=CS2,`3`=CS1,`4`=CS1,`5`=CS1,`6`=CS1,`7`=CS1,`8`=CS1,`9`=CS1,`10`=CS1,`11`=CS1,`12`=CS1,`13`=CS1,`14`=CS1,`15`=CS1))
addPicture("Lift.png", sheet5, scale = 1, startRow = 3,startColumn = 7)
saveWorkbook(wb, "Decile_Analysis.xlsx")
